### ISSUE TITLE
Small & Medium ribbon buttons disappearing

### ISSUE THREAD

**Issue by SpeeQz1** [APEbbers/FreeCAD-Ribbon#110] opened 2024-11-17 18:23 UTC
For some reason specifically small ribbon buttons like "Add a Primitive", "Subtractive Box" simply do not appear unless set to a Large size.

( Separator added to more clearly show the buttons, without it both buttons don't appear )
![image](https://github.com/user-attachments/assets/baf3f8b9-4070-4711-9c03-a59a879f011b)
![image](https://github.com/user-attachments/assets/c391d0da-adef-412c-b754-556a301f633c)
![image](https://github.com/user-attachments/assets/a3a854fd-e290-46b2-979b-662db93afb93)

( Without separator )
![image](https://github.com/user-attachments/assets/3875c958-a4c9-4300-baa1-26b9e1d9e16e)
![image](https://github.com/user-attachments/assets/64247759-5ebc-4011-99ab-84c1f8f273f5)

```
OS: Linux Mint 22 (X-Cinnamon/cinnamon/xcb)
Architecture: x86_64
Version: 1.0.0RC4.39104 (Git) Conda AppImage
Build type: Release
Branch: (HEAD detached at 1.0rc4)
Hash: 83646753e051eaf438c0d5e9351cb57bd27377ab
Python 3.11.9, Qt 5.15.13, Coin 4.0.3, Vtk 9.2.6, OCC 7.7.2
Locale: English/United States (en_US)
Stylesheet/Theme/QtStyle: OpenDark.qss/OpenDark/Fusion
Installed mods: 
  * fasteners 0.5.29 (Disabled)
  * lattice2 1.0.0
  * Manipulator 1.5.7
  * CurvedShapes 1.0.13
  * FreeCAD-Ribbon 1.4.0
  * SearchBar 1.0.2
  * Backups
  * OpenTheme 2024.9.1
```

**Comment by APEbbers** [comment] 2024-11-17 20:40
Hi,

I've looked into it. apparently there is a maximum of 13 columns (separators included). There is no obvious parameter in PyQtRibbon, but i've now set that everything beyond 13 columns will added in the overflow panel.

For now, i close the issue. if i find the parameter, I'll set the maximum bigger

**Comment by SpeeQz1** [comment] 2024-11-17 22:26
@APEbbers Tried the latest Develop build with the changes and I still seem to have the same issues.
![image](https://github.com/user-attachments/assets/98e00ed9-3169-4a15-8b47-e100ef0f8f00)

**Comment by APEbbers** [comment] 2024-11-17 22:30
If you set the maximum number of columns to 6. Do you see then a button like this?
![image](https://github.com/user-attachments/assets/72149364-8e94-4c57-805d-a20455d55fb7)

and if so, are the buttons then in the extra menu?

**Comment by SpeeQz1** [comment] 2024-11-17 22:33
Yep the overflow button does appear. Although it seems to not appear for the default value (mine was 0).

**Comment by APEbbers** [comment] 2024-11-17 22:40
And if you set the number of columns to 12?

I have it at 0 and it shows this (internally this is 13 or more):
![image](https://github.com/user-attachments/assets/c76a238e-b682-4212-b9c2-1a1f41f1c8df)

**Comment by SpeeQz1** [comment] 2024-11-17 22:42
Still is missing.
![image](https://github.com/user-attachments/assets/7f2de913-75b6-4ab7-b0df-b9e5f857e856)
![image](https://github.com/user-attachments/assets/2d3b8f92-c8f8-4ce3-a835-6ae80de595a6)

**Comment by APEbbers** [comment] 2024-11-17 22:52
I've set the maximum to 10. In my virtual Linux, the buttons are now showing. Can you give it a try?

**Comment by SpeeQz1** [comment] 2024-11-17 22:58
![image](https://github.com/user-attachments/assets/a174bf76-d049-414e-9968-c3f53742952f)

**Comment by SpeeQz1** [comment] 2024-11-18 17:29
Hopefully the default would be changed as subtractive loft is missing or the bug is somehow fixed for the maximum number of columns.

**Comment by APEbbers** [comment] 2024-11-18 18:35
If you click on the arrow, button, is the missing button there?

**Comment by APEbbers** [comment] 2024-11-18 18:53
I think I've found it. There were some strange size policies needed for panels.
I've tested it on both windows and linux mint (VirtualBox) with FC1.0 QT6.

Can you try if it also works on your side?

**Comment by SpeeQz1** [comment] 2024-11-18 19:02
Seems to have worked although now the additive and subtractive pipes are separated by a separator.

![image](https://github.com/user-attachments/assets/47fb20e3-877b-455f-b023-9d8e3664b672)

**Comment by APEbbers** [comment] 2024-11-18 19:39
I had to add a separator between the boolan and the smaller icons. After that, it is it was intended again
![image](https://github.com/user-attachments/assets/f4a93146-19ab-4567-807b-2d666e394397)

**Closed as completed** 2024-11-18 21:20 UTC
Labels: Further investigation needed
